export const admins = [
  {
    id: 1,
    name: "Ahmed Khan",
    school: "Beaconhouse School",
    email: "ahmed@beacon.edu",
    phone: "+92 300 1112223",
    status: "Active",
    username: "ahmed_admin",
    password: "password123",
    profileImage: null,
  },
  {
    id: 2,
    name: "Sara Malik",
    school: "City School",
    email: "sara@city.edu",
    phone: "+92 333 4445556",
    status: "Active",
    username: "sara_admin",
    password: "password123",
    profileImage: null,
  },
  {
    id: 3,
    name: "Zain Ali",
    school: "Roots International",
    email: "zain@roots.edu",
    phone: "+92 345 6667778",
    status: "Inactive",
    username: "zain_admin",
    password: "password123",
    profileImage: null,
  },
  {
    id: 4,
    name: "Fatima Noor",
    school: "LGS School",
    email: "fatima@lgs.edu",
    phone: "+92 321 0009998",
    status: "Active",
    username: "fatima_admin",
    password: "password123",
    profileImage: null,
  },
];
